language: cpp
script:
 - export PYTHON_BIN=/usr/bin/python
 - ./tools/travis-scripts/run-script.sh
before_install:
 - ./tools/travis-scripts/before-install.sh
env:
  matrix:
  - PLATFORM=android
branches:
  only:
    - master
    - develop
