language: cpp
script:
- export PYTHON_BIN=/usr/bin/python
- ./tools/travis-scripts/run-script.sh
before_install:
- ./tools/travis-scripts/before-install.sh
env:
  matrix:
  - GEN_BINDING=YES
  - PLATFORM=android
  global:
  - secure: OGa02D+rEO8a3+UqkQbhyyse+7EWtoXJHQiWnf5nd2LQB4cFGFY5B3UjLUsi4NOkg9ummNwqEeaDkLdHLyrtN22w1vP14ERfR17l8YukGL8cv600O3hzHNTAGZ0dBH0u6TCIZ6jDjTiTQ5MMeRgXxCSBjUdT7rotITfXlB1HPXQ=
  - secure: Nim7rHipAlLu6TzwCwJxkPDdZgbGqHtImwtmIfhJfcO7Kk/4GOokCrfaUEa5boXx9a+YG2B9APGjuZ84NMFz/pLJDuIFWdH+i3tQSuKR+DPoAYQ4TqG+1l+sQM28ogef7SAzNHKB6LfcM+v5MRn+rvI50mmixvQXkq1h1rg0Eqg=
  - secure: dM4ecCO+w6ZNH0Gc3xNS8YmmxNtiNslpD9xkQVKRubj4Dlycjg2yBgX+pqxn4/YHGYBWSaY5CwxctWr2El0bx+i6kyHV+0WrfnMoyAygcE5S9Qe+JjA8j+Ecz/r2dE626XHz/eGN/sm9iMTUsyziJIXvJXaVJPglPrzYXL/xLHg=
branches:
  only:
  - master
  - develop
